name: Release (Private Packages)
on:
  workflow_dispatch:
jobs:
  version_or_release:
    name: 'Version and open PR (or) release private packages'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        
      - uses: pnpm/action-setup@v4
        with:
          version: 6.14.5  # Specify the pnpm version here
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: create pnpm store directory
        run: mkdir -p ~/.pnpm-store
      - name: setup pnpm store config
        run: pnpm config set store-dir ~/.pnpm-store
      - name: install dependencies
        run: pnpm install --frozen-lockfile
