name: Reproduce Yarn Cache Issue
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  CI: true
jobs:
  reproduce_issue:
    name: 'Reproduce Yarn Cache Issue'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_RUNNER }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.HOST_DEV }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.HOST_USER }}@${{ secrets.HOST_DEV }} << 'EOF'
            set -e
            cd /home/app
            echo "Checking out dev branch"
            git checkout dev || { echo "Failed to checkout dev branch"; exit 1; }
            echo "Pulling latest changes from dev branch"
            git pull origin dev || { echo "Failed to pull latest changes"; exit 1; }
            echo "Installing dependencies"
            yarn || { echo "Failed to install dependencies"; exit 1; }
            echo "Running database migrations"
            yarn db:migrate || { echo "Failed to run database migrations"; exit 1; }
            echo "Restarting application"
            pm2 restart crm_backend || { echo "Failed to restart application"; exit 1; }
          EOF
 
