name: Reproduce Yarn Cache Issue
on:
  workflow_dispatch:

jobs:
  reproduce_issue:
    runs-on: self-hosted
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
            ref: dev
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 20
           cache: 'yarn'
           cache-dependency-path: '**/yarn.lock'

       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.9.0
         with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_RUNNER }}

       - name: Add SSH known hosts
         run: |
            mkdir -p ~/.ssh
            ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.HOST_DEV }} >> ~/.ssh/known_hosts

       - name: Deploy to server
         run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.HOST_USER }}@${{ secrets.HOST_DEV }} << 'EOF'
          cd /home/app
          # Debugging: Print PATH and check for Node.js and Yarn
            echo "Current PATH: $PATH"
            which node || echo "Node.js not found"
            which yarn || echo "Yarn not found"

            # Ensure Node.js is installed
            if ! command -v node &> /dev/null
            then
              echo "Node.js not found, installing..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Ensure Yarn is installed
            if ! command -v yarn &> /dev/null
            then
              echo "Yarn not found, installing..."
              npm install -g yarn
            fi
          git checkout dev
          git pull origin dev
          yarn
          yarn db:migrate
          pm2 restart crm_backend
          EOF
 
