name: Release (Private Packages)
on:
  workflow_dispatch:
jobs:
  version_or_release:
    name: 'Version and open PR (or) release private packages'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
   

      - name: Install Dependencies
        run: yarn install        
 
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "18"
          cache: "yarn"

      
      


      
      
     
     
